spring:
    application:
        name: first-service
    rabbitmq:
        address: amqp://guest@127.0.0.1:15672/
        host: localhost
        port: 5672
        username: guest
        password: guest
        exchange: Greetings
server:
    port: 
        8081
eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka